
language: node_js

cache:
  directories:
  - node_modules

script:
- npm run build
- npm test

deploy:
  provider: npm
  email: mail@jonasw.de
  api_key:
    secure: Dspl9oPtOz+wsCVVGiYQWxfKusCUuAl92urGWxTt/TIT0bpDKmcgk0neMyYSd5CSvWqpjqEgGdXo66Ra4TIQ+6JnMY4jpd3CDFprCQJOFWCks2UWVtEXo1UkQLhDKntWVHTiBtQsP19BeoaHVJbcyX3Edwro8CwRiV36kBjPjL00nBV00caVCmK3SPQiJDs4GotR1FAl2HBr0bjp7QV/I7vzkh69xsKTE4qkROEr1knI/g/z06eo0tKEf4RPks1t3kZBg26xzkDNSgL71fivOK8t1gSoZGugSmpxwaQI09fjFGsZwfCGA1lGjrBgsWn2B4RWAY7v9XCt+nZql2iah2l6FjvArLF806vslgNlsBOcZtb3DiznaccwXKVdvIAeTIIMCEUSe0Lz699xDv8bT0YLNCwhw460Dup3tREK9JhebiyXpNgklJrrGkSHYYfjabjLLGX8yWKLG/DBnDMbmrKXVDU+Up0rara9QLcP6LAqI/nWxpG5eQW80Sx18dBXOweo1bWmafUj3iUuOiuPax0660nqR9rXBgBUMq8FP/5LOaRdbrcGHjMpszQvNqb6j2zWR6cGrEVWjjidSNihFRDIK2V91tnTT303cAtQYnvw/IE7ueI3UGiG3s+vX9k8Ug96lZHhJTAnS9hBuOidTelcHMgu46x08JblVPReE0E=
  on:
    tags: true
    repo: thriqon/parola
